package com.houdert6.papermixins;

import com.houdert6.papermixins.data.PaperMixinConfig;
import com.houdert6.papermixins.mixinservices.PaperMixinBootstrapService;
import com.houdert6.papermixins.mixinservices.PaperMixinService;
import io.papermc.paper.plugin.bootstrap.BootstrapContext;
import io.papermc.paper.plugin.bootstrap.PluginBootstrap;
import io.papermc.paper.plugin.bootstrap.PluginProviderContext;
import joptsimple.OptionParser;
import joptsimple.OptionSet;
import joptsimple.util.PathConverter;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.logger.slf4j.ComponentLogger;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;
import org.spongepowered.asm.launch.MixinBootstrap;
import org.spongepowered.asm.mixin.MixinEnvironment;
import org.spongepowered.asm.mixin.Mixins;

import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.stream.Stream;

public class PaperMixinsBootstrap implements PluginBootstrap {
    private static PaperMixinsClassLoader loader = null;
    private static ComponentLogger bootstrapLogger;
    private static final List<PaperMixinConfig> MIXINS = new ArrayList<>();
    /**
     * config.yml
     */
    private FileConfiguration config;
    private boolean isRunning = true;

    @Override
    public void bootstrap(@NotNull BootstrapContext context) {
        Path mixinsFolder = context.getDataDirectory().resolve("mixins");
        if (!Files.isDirectory(mixinsFolder)) {
            try {
                Files.createDirectories(mixinsFolder); // Create a mixins folder. This is done before checking the config so both the folder and config end up getting generated on first run, since the config is generated by the usual means outside of plugin bootstrap. createDirectories() is used since the plugin folder doesn't exist yet and hasn't been made through conventional means
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        if (!Files.isRegularFile(context.getDataDirectory().resolve("config.yml"))) {
            context.getLogger().warn(Component.text("A config.yml will be generated for you shortly, as with any other plugin. Please configure it or else PaperMixins will not load your mixins!"));
            return;
        }
        config = YamlConfiguration.loadConfiguration(context.getDataDirectory().resolve("config.yml").toFile());
        if (!config.isList("java-args")) {
            context.getLogger().warn(Component.text("config.yml has not been configured yet. Please configure it or else PaperMixins will not load your mixins!"));
            return;
        }
        try (Stream<Path> files  = Files.list(mixinsFolder)) {
            files.forEach(path -> {
                if (!Files.isRegularFile(path))
                    return;
                try (JarFile jar = new JarFile(path.toFile())) {
                    JarEntry entry = jar.getJarEntry("papermixins.yml");
                    if (entry != null) {
                        try (InputStream configStream = jar.getInputStream(entry); InputStreamReader reader = new InputStreamReader(configStream)) {
                            PaperMixinConfig config = new PaperMixinConfig(reader);
                            config.pluginPath = path;
                            if (config.name != null && config.mixinConfig != null) {
                                MIXINS.add(config);
                            } else {
                                context.getLogger().warn(Component.text("Mixins jar " + path + " is not a valid mixin-containing jar"));
                            }
                        }
                    }
                } catch (Exception ignored) { }
            });
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        if (MIXINS.isEmpty()) {
            context.getLogger().info(Component.text("No mixins were found! PaperMixins will allow the server to load normally without initializing the Mixin subsystem, since it is not needed."));
            return;
        }
        if (PaperMixinsClassLoaderUtils.isPreMixin()) {
            initMixinSubsystem(context); // Mixins were found and everything is properly configured, the Mixin subsystem can finally be loaded!
        }
    }

    /**
     * A method that should only be called before Mixin is initialized. After Mixin is initialized and during the second run of main(), the PaperMixins ClassLoader will (with manual ASM, not Mixin), patch {@link PaperMixinsClassLoaderUtils#isPreMixin()} isPreMixin()} to return false, so any calls to this method should be wrapped in an if statement with a call to that method.
     */
    private void initMixinSubsystem(@NotNull BootstrapContext context) {
        bootstrapLogger = context.getLogger();
        URL[] mixinUrls = new URL[MIXINS.size()];
        for (int i = 0; i < mixinUrls.length; i++) {
            try {
                mixinUrls[i] = MIXINS.get(i).pluginPath.toUri().toURL();
            } catch (MalformedURLException e) {
                throw new RuntimeException(e);
            }
        }
        loader = new PaperMixinsClassLoader(mixinUrls, PluginBootstrap.class.getClassLoader());
        System.setProperty("mixin.bootstrapService", PaperMixinBootstrapService.class.getName());
        System.setProperty("mixin.service", PaperMixinService.class.getName());
        MixinBootstrap.init();
        // Register each mixin
        for (PaperMixinConfig config : MIXINS) {
            Mixins.addConfiguration(config.mixinConfig);
        }
        // Enable Mixin
        try {
            Method gotoPhase = MixinEnvironment.class.getDeclaredMethod("gotoPhase", MixinEnvironment.Phase.class);
            gotoPhase.setAccessible(true);
            gotoPhase.invoke(null, MixinEnvironment.Phase.INIT);
            gotoPhase.invoke(null, MixinEnvironment.Phase.DEFAULT);
            // Load main (again)
            Class<?> main = loader.loadClass("net.minecraft.server.Main", true);
            Method mainMethod = main.getMethod("main", loader().loadClass(OptionSet.class.getName()));
            Class<?> paperMixinsClassLoaderUtilsClass = loader.loadClass(PaperMixinsClassLoaderUtils.class.getName());
            Method optionParser = paperMixinsClassLoaderUtilsClass.getDeclaredMethod("optionParser");
            optionParser.setAccessible(true);
            Object parser = optionParser.invoke(null);
            Method parse = Arrays.stream(parser.getClass().getMethods()).filter(m -> m.getName().equals("parse")).findFirst().orElseThrow();
            // Start the server with mixins
            Object optionSet = parse.invoke(parser, (Object)config.getStringList("java-args").toArray(new String[0]));
            Thread serverThread = new Thread(() -> {
                try {
                    mainMethod.invoke(null, optionSet);
                } catch (IllegalAccessException | InvocationTargetException e) {
                    throw new RuntimeException(e);
                }
            });
            serverThread.setContextClassLoader(loader);
            serverThread.start();
            serverThread.join();
            // serverThread actually ends when Minecraft starts starting, so we need to sleep until the JVM starts stopping, to prevent the pre-mixin code continuing to run
            Object condVar = new Object();
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                synchronized (condVar) {
                    isRunning = false;
                    condVar.notify();
                }
            }));
            while (isRunning) {
                synchronized (condVar) {
                    condVar.wait();
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static ComponentLogger logger() {
        return bootstrapLogger;
    }
    public static PaperMixinsClassLoader loader() {
        return loader;
    }
    public static List<PaperMixinConfig> getMixins() {
        return Collections.unmodifiableList(MIXINS);
    }
}
